# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-10 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=50)),
                ('head', models.FileField(upload_to='./upload/')),
            ],
        ),
    ]
