# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-15 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zhihuApp', '0002_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('release_date', models.DateField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhihuApp.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhihuApp.User')),
            ],
        ),
    ]
