# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-15 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhihuApp', '0003_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(),
        ),
    ]
