# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-21 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zhihuApp', '0004_auto_20170315_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectionname', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhihuApp.Answers')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhihuApp.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhihuApp.User')),
            ],
        ),
    ]
